# Prepocesamiento de Datos con Python
## FES Arag√≥n
### ICO --- Sesion 03
#### Alexis Cano Tapia

In [1]:
import pandas as pd

In [2]:
! pip install "pymongo[srv]"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymongo[srv] in c:\programdata\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from pymongo[srv]) (2.3.0)

In [3]:
import pymongo

## Conexion con Mongo

In [4]:
usuario = 'fesalu'
passwd = 'nosqlfes123'
cluster = 'cluster0-shard-00-00.8pyt4.mongodb.net'
n1 = 'cluster0-shard-00-01.8pyt4.mongodb.net'
n2 = 'cluster0-shard-00-02.8pyt4.mongodb.net'
puerto = '27017'
mongo_str = f"mongodb://{usuario}:{passwd}@{cluster}:{puerto},{n1}:{puerto},{n2}:{puerto}/?ssl=true&replicaSet=atlas-nok9e6-shard-0&authSource=admin&retryWrites=true&w=majority"
print(mongo_str)
mongoClient = pymongo.MongoClient(mongo_str)
mongoClient

mongodb://fesalu:nosqlfes123@cluster0-shard-00-00.8pyt4.mongodb.net:27017,cluster0-shard-00-01.8pyt4.mongodb.net:27017,cluster0-shard-00-02.8pyt4.mongodb.net:27017/?ssl=true&replicaSet=atlas-nok9e6-shard-0&authSource=admin&retryWrites=true&w=majority

MongoClient(host=['cluster0-shard-00-01.8pyt4.mongodb.net:27017', 'cluster0-shard-00-02.8pyt4.mongodb.net:27017', 'cluster0-shard-00-00.8pyt4.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='atlas-nok9e6-shard-0', authsource='admin', retrywrites=True, w='majority', tls=True)

In [5]:
#Ver todas las bases de datos disponilbes
mongoClient.list_database_names()

['OmarMendozaGonzalez',
 'agenda',
 'colegio',
 'fundamentosmongo',
 'itsa',
 'pdcd',
 'taller',
 'tbd',
 'tebd',
 'admin',
 'local']

In [6]:
db = mongoClient.colegio
db

Database(MongoClient(host=['cluster0-shard-00-01.8pyt4.mongodb.net:27017', 'cluster0-shard-00-02.8pyt4.mongodb.net:27017', 'cluster0-shard-00-00.8pyt4.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='atlas-nok9e6-shard-0', authsource='admin', retrywrites=True, w='majority', tls=True), 'colegio')

In [7]:
f = db.alumnos.find({'curp': { '$exists': 0 }})
f

In [8]:
lista_f = list(f)
lista_f

[{'_id': ObjectId('5f873e4a7591b0b48f65faf9'),
  'clave_alu': 11030177,
  'ap_paterno': 'FERRUSCA',
  'ap_materno': 'ANDRADE',
  'nombre': 'OCTAVIO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'tavoferrus_11@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65faf6'),
  'clave_alu': 11030172,
  'ap_paterno': 'BORBOLLA',
  'ap_materno': 'RAMOS',
  'nombre': 'ARGELIA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'kargi_gogos@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fafc'),
  'clave_alu': 11030199,
  'ap_paterno': 'ROSALES',
  'ap_materno': 'APREZA',
  'nombre': 'NESTOR MARTIN',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'nestoriwh@hotmai.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb04'),
  'clave_alu': 11030217,
  'ap_paterno': 'FERRUSCA',
  'ap_materno': 'ANDRADE',
  'nombre': 'CESAR',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'cesar_tum-b@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fafb'),
  'clave_alu': 11030173,
  'ap_paterno': 'CASTRO',
  'ap_materno': 'MANCERA',
  'nombre': 'KARLA MARIANA',
  'sexo': 'F',
  'ciudad': 'SANTIAGO DE QUERETARO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb0b'),
  'clave_alu': 11030242,
  'ap_paterno': 'ALCOCER',
  'ap_materno': 'ESCOBAR',
  'nombre': 'AGUSTIN',
  'sexo': 'M'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb06'),
  'clave_alu': 11030232,
  'ap_paterno': 'PEREZ',
  'ap_materno': 'DEL CASTILLO VELASCO',
  'nombre': 'ESTEBAN',
  'email': 'estebanlunete@yahoo.com.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb13'),
  'clave_alu': 11030273,
  'ap_paterno': 'URIBE',
  'ap_materno': 'GARCIA',
  'nombre': 'MARIA GUADALUPE',
  'ciudad': 'QUERETARO',
  'email': 'misato227@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb08'),
  'clave_alu': 11030235,
  'ap_paterno': 'SAAVEDRA',
  'ap_materno': 'MARTINEZ',
  'nombre': 'GABRIEL ANDRES',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'gasaa_10@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb17'),
  'clave_alu': 11030292,
  'ap_paterno': 'PEREA',
  'ap_materno': 'PACHECO',
  'nombre': 'FERNANDO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb0e'),
  'clave_alu': 11030213,
  'ap_paterno': 'COSS',
  'ap_materno': 'AGUADO',
  'nombre': 'RAUL ANDRES',
  'ciudad': 'QUERETARO',
  'email': 'andrescoss285@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb11'),
  'clave_alu': 11030268,
  'ap_paterno': 'MONTIEL',
  'ap_materno': 'PEREZ',
  'nombre': 'CARLOS GABRIEL',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'gabos_1803@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fafe'),
  'clave_alu': 11030204,
  'ap_paterno': 'VAZQUEZ',
  'ap_materno': 'GONZALEZ',
  'nombre': 'ROBERTO',
  'sexo': 'M',
  'ciudad': 'SANTIAGO DE QUERETARO',
  'email': 'rob_vaz03@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb1d'),
  'clave_alu': 11040003,
  'ap_paterno': 'BARRON',
  'ap_materno': 'LOEZA',
  'nombre': 'GABRIELA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'gabybalo89@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb21'),
  'clave_alu': 11040021,
  'ap_paterno': 'HERNANDEZ',
  'ap_materno': 'MORENO',
  'nombre': 'MARIA JOSE',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'mahemo_10@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb28'),
  'clave_alu': 11040046,
  'ap_paterno': 'AGUIRRE',
  'ap_materno': 'MARGAIN',
  'nombre': 'LAURA ALEJANDRA'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb2e'),
  'clave_alu': 11040035,
  'ap_paterno': 'PEREZ',
  'ap_materno': 'RETANA',
  'nombre': 'DANIEL',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'oraciones_9@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb30'),
  'clave_alu': 11040043,
  'ap_paterno': 'VAZQUEZ',
  'ap_materno': 'ARTEAGA',
  'nombre': 'THALIA IVETTE',
  'sexo': 'F'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb33'),
  'clave_alu': 11040069,
  'ap_paterno': 'MARUSICH',
  'ap_materno': 'CASTELLANOS',
  'nombre': 'ANDRES',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'marucholey@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb32'),
  'clave_alu': 11040044,
  'ap_paterno': 'VEGA',
  'ap_materno': 'VEGA',
  'nombre': 'ELIZABETH',
  'ciudad': 'QUERETARO',
  'email': 'liznena1@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb38'),
  'clave_alu': 11040074,
  'ap_paterno': 'OTERO',
  'ap_materno': 'GARABATOS',
  'nombre': 'SANTIAGO',
  'sexo': 'M',
  'email': 'mirameahuevo@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb3a'),
  'clave_alu': 11040092,
  'ap_paterno': 'ARANDA',
  'ap_materno': 'CALZADA',
  'nombre': 'MAYELA AMAYRANI'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb3f'),
  'clave_alu': 11040094,
  'ap_paterno': 'AYALA',
  'ap_materno': 'ALCANTARA',
  'nombre': 'ELVIRA DE JESUS',
  'sexo': 'F',
  'ciudad': 'QUER',
  'email': 'badgirl_2501@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb1f'),
  'clave_alu': 11040010,
  'ap_paterno': 'DEL CORRAL',
  'ap_materno': 'GUERRERO',
  'nombre': 'ABRAHAM',
  'sexo': 'F'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb48'),
  'clave_alu': 11040141,
  'ap_paterno': 'BRAVO',
  'ap_materno': 'CORONILLA',
  'nombre': 'JOSE ANTONIO',
  'sexo': 'M',
  'ciudad': 'SANTIAGO DE QUER',
  'email': 'a_coronilla@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb44'),
  'clave_alu': 11040128,
  'ap_paterno': 'ROMAN',
  'ap_materno': 'AGUILAR',
  'nombre': 'ZIMRI',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'zimrirw@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb3c'),
  'clave_alu': 11040078,
  'ap_paterno': 'RODRIGUEZ',
  'ap_materno': 'IBARRA',
  'nombre': 'CHRISTIAN ARTURO',
  'ciudad': 'QUERETARO',
  'email': 'oco_1589@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb3d'),
  'clave_alu': 11040104,
  'ap_paterno': 'GARCIA',
  'ap_materno': 'GONZALEZ',
  'nombre': 'DAVID SALOMON',
  'sexo': 'M'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb4a'),
  'clave_alu': 11040144,
  'ap_paterno': 'CASILLAS',
  'ap_materno': 'PINEDA',
  'nombre': 'NORMA SELENE',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'selenotalobuenaonda@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb52'),
  'clave_alu': 11040148,
  'ap_paterno': 'DOMINGUEZ',
  'ap_materno': 'GARCIA',
  'nombre': 'PAULO CESAR',
  'sexo': 'M',
  'ciudad': 'QUERETARO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb39'),
  'clave_alu': 11040090,
  'ap_paterno': 'ZORRILLA',
  'ap_materno': 'TREJO',
  'nombre': 'LERNA ISSARHELLY',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'lerna_320@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb41'),
  'clave_alu': 11040113,
  'ap_paterno': 'NOGUES',
  'ap_materno': 'BARAJAS',
  'nombre': 'MARIA FERNANDA',
  'sexo': 'F',
  'ciudad': 'MEXICO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb43'),
  'clave_alu': 11040116,
  'ap_paterno': 'PARRA',
  'ap_materno': 'MARTINEZ',
  'nombre': 'ERICK IVAN',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'coery_parra@homail.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb40'),
  'clave_alu': 11040109,
  'ap_paterno': 'LOPEZ',
  'ap_materno': 'CUEVAS',
  'nombre': 'OLIVIA DEL CARMEN',
  'ciudad': 'QUERETARO',
  'email': 'oli_car@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb54'),
  'clave_alu': 11040157,
  'ap_paterno': 'LOARCA',
  'ap_materno': 'GONZALEZ',
  'nombre': 'ALEJANDRA NOEMI',
  'sexo': 'F',
  'ciudad': 'QUERETARO MEXICO',
  'email': 'ale_loarca@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb5c'),
  'clave_alu': 11040167,
  'ap_paterno': 'REYNOSO',
  'ap_materno': 'SANCHEZ',
  'nombre': 'LUIS RENE',
  'ciudad': 'SANTIAGO DE QRO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb55'),
  'clave_alu': 11040158,
  'ap_paterno': 'LOPEZ',
  'ap_materno': 'BARBA',
  'nombre': 'ANAKAREM',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'pingu_ina03@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb50'),
  'clave_alu': 11040154,
  'ap_paterno': 'HURTADO',
  'ap_materno': 'MENDEZ',
  'nombre': 'JIMENA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'prinsess_1506@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb42'),
  'clave_alu': 11040122,
  'ap_paterno': 'RAMIREZ',
  'ap_materno': 'LEGORRETA',
  'nombre': 'ALEJANDRA',
  'ciudad': 'QUERETARO',
  'email': 'amaya2907@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb4b'),
  'clave_alu': 11040145,
  'ap_paterno': 'CASTRO',
  'ap_materno': 'FLORES',
  'nombre': 'DANIEL EDUARDO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'dani_hots@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb53'),
  'clave_alu': 11040156,
  'ap_paterno': 'LEON',
  'ap_materno': 'ZARATE',
  'nombre': 'NICOLAS',
  'sexo': 'M',
  'ciudad': 'QUERETARO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb68'),
  'clave_alu': 11040186,
  'ap_paterno': 'BAUTISTA',
  'ap_materno': 'SILVA',
  'nombre': 'LUIS MOISES',
  'ciudad': 'QUERETARO',
  'email': 'luis.bautista@municipiodequeretaro.gob.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb67'),
  'clave_alu': 11040187,
  'ap_paterno': 'CARRASCO',
  'ap_materno': 'DORANTES',
  'nombre': 'ANA DEL CARMEN',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'ani_ta_car@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb64'),
  'clave_alu': 11040181,
  'ap_paterno': 'AGUILAR',
  'ap_materno': 'TORRES',
  'nombre': 'HECTOR MAURICIO',
  'sexo': 'M',
  'email': 'maria.torres@autoliv.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb75'),
  'clave_alu': 11040202,
  'ap_paterno': 'MARTIN',
  'ap_materno': 'RODRIGUEZ',
  'nombre': 'JOSE MANUEL',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'martinsoyelre@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb7b'),
  'clave_alu': 11040212,
  'ap_paterno': 'RIVERA',
  'ap_materno': 'RAMIREZ',
  'nombre': 'ALEJANDRA',
  'sexo': 'F',
  'ciudad': 'QUER',
  'email': 'aleja_rira@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb6c'),
  'clave_alu': 11040191,
  'ap_paterno': 'DORANTES',
  'ap_materno': 'ASPEITIA',
  'nombre': 'GUADALUPE',
  'ciudad': 'QUERETARO',
  'email': 'dorantes.oscar@mx.sika.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb83'),
  'clave_alu': 11040225,
  'ap_paterno': 'ALVARADO',
  'ap_materno': 'SALAZAR',
  'nombre': 'MANUEL',
  'sexo': 'M',
  'ciudad': 'SANTIAGO DE QUERETARO',
  'email': 'the_human_disco_ball@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb87'),
  'clave_alu': 11040234,
  'ap_paterno': 'ESCUDERO',
  'ap_materno': 'OSORNO',
  'nombre': 'KARLA PAULINA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'pausitamosha_escudero@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb7c'),
  'clave_alu': 11040211,
  'ap_paterno': 'RIVERA',
  'ap_materno': 'ESPINOSA',
  'nombre': 'MARIO ALBERTO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'mario_6003@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb8b'),
  'clave_alu': 11040240,
  'ap_paterno': 'GARCIA',
  'ap_materno': 'GOMEZ',
  'nombre': 'MAYRA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'mayra_92g@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb7d'),
  'clave_alu': 11040213,
  'ap_paterno': 'RODRIGUEZ',
  'ap_materno': 'JUAREZ',
  'nombre': 'MARIO ENRIQUE',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'mariobross922@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb6e'),
  'clave_alu': 11040193,
  'ap_paterno': 'GIL',
  'ap_materno': 'SOLIS',
  'nombre': 'MIGUEL ANGEL',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'solisgil@prodigy.net.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb85'),
  'clave_alu': 11040231,
  'ap_paterno': 'CASTILLO',
  'ap_materno': 'MARTELL',
  'nombre': 'JESSICA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'jesicuda_11@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb8e'),
  'clave_alu': 11040242,
  'ap_paterno': 'HERNANDEZ',
  'ap_materno': 'GUTIERREZ',
  'nombre': 'EDITH VERONICA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'rimix_3@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb8f'),
  'clave_alu': 11040244,
  'ap_paterno': 'LANDAVERDE',
  'ap_materno': 'MARTINEZ',
  'nombre': 'JORGE DAVID',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'avelinamr@yahoo.com.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb79'),
  'clave_alu': 11040206,
  'ap_paterno': 'NU',
  'ap_materno': 'GALLEGOS',
  'nombre': 'ANETTE ITHABICO',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'ana_4228@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb62'),
  'clave_alu': 11040176,
  'ap_paterno': 'TOVAR',
  'ap_materno': 'LOPEZ',
  'nombre': 'FILIBERTO',
  'sexo': 'M',
  'ciudad': 'QUERETATO',
  'email': 'f_tovar992@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb90'),
  'clave_alu': 11040237,
  'ap_paterno': 'ESPINOZA',
  'ap_materno': 'GARCIA',
  'nombre': 'EDGAR ISRAEL',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'edgar_51193@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb9f'),
  'clave_alu': 11040266,
  'ap_paterno': 'YA',
  'ap_materno': 'ROBLES',
  'nombre': 'HONORIO IVAN',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'honoriogym@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fba1'),
  'clave_alu': 11040267,
  'ap_paterno': 'AGUILAR',
  'ap_materno': 'TORRES',
  'nombre': 'JOSE RODRIGO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'maria.torres@autoliv.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fb78'),
  'clave_alu': 11040207,
  'ap_paterno': 'OROZCO',
  'ap_materno': 'YA',
  'nombre': 'STEFANIA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'stufda_9@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fba7'),
  'clave_alu': 11040280,
  'ap_paterno': 'GUERRA',
  'ap_materno': 'VAZQUEZ',
  'nombre': 'NORMANN',
  'ciudad': 'SANTIAGO DE QUERETARO',
  'email': 'h2ozarca@yahoo.com.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbb0'),
  'clave_alu': 11040289,
  'ap_paterno': 'MARTINEZ',
  'ap_materno': 'TELLEZ',
  'nombre': 'MARCELA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'ki92marce594-22@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbaf'),
  'clave_alu': 11040286,
  'ap_paterno': 'LOPEZ',
  'ap_materno': 'MONROY',
  'nombre': 'DIEGO ANTONIO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'elisabetmonroy@yahoo.com.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbb1'),
  'clave_alu': 11040290,
  'ap_paterno': 'MARTINEZ',
  'ap_materno': 'VILLAGRANA',
  'nombre': 'ANDREA ALICIA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'andypets_92@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbb2'),
  'clave_alu': 11040291,
  'ap_paterno': 'MATA',
  'ap_materno': 'ARELLANO',
  'nombre': 'OSCAR ANDRES',
  'ciudad': 'SANTIAGO DE QUERETARO',
  'email': 'omatagar@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbbd'),
  'clave_alu': 11040308,
  'ap_paterno': 'ZARATE',
  'ap_materno': 'RODRIGUEZ',
  'nombre': 'MARIA DEL CARMEN',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'mary_mczr@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbbf'),
  'clave_alu': 11050016,
  'ap_paterno': 'GAYOL',
  'ap_materno': 'DE LA TORRE',
  'nombre': 'JOSEFINA',
  'ciudad': 'QUER',
  'email': 'algebrita@algebrita.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbbc'),
  'clave_alu': 11040300,
  'ap_paterno': 'ROCHA',
  'ap_materno': 'NOVOA',
  'nombre': 'EDUARDO',
  'ciudad': 'QUERETARO',
  'email': 'eduardo_53@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbc4'),
  'clave_alu': 11050026,
  'ap_paterno': 'OBESO',
  'ap_materno': 'MARTINEZ',
  'nombre': 'TANIA CAROLINA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': '1968ed@prodigy.net.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbaa'),
  'clave_alu': 11040281,
  'ap_paterno': 'GUERRERO',
  'ap_materno': 'ALMANZA',
  'nombre': 'MIGUEL OMAR',
  'ciudad': 'QUERETARO',
  'email': 'moga2415_@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbc9'),
  'clave_alu': 11050034,
  'ap_paterno': 'SOBERON',
  'ap_materno': 'URBIOLA',
  'nombre': 'JAVIER EUGENIO',
  'ciudad': 'QUERETARO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbc8'),
  'clave_alu': 11050032,
  'ap_paterno': 'SANTOYO',
  'ap_materno': 'MORALES',
  'nombre': 'MARIA FERNANDA',
  'sexo': 'F'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbca'),
  'clave_alu': 11050037,
  'ap_paterno': 'UGALDE',
  'ap_materno': 'MEZA',
  'nombre': 'SAMUEL ULISES',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'samuel_m23@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbb4'),
  'clave_alu': 11040295,
  'ap_paterno': 'RAMOS',
  'ap_materno': 'MARTINEZ',
  'nombre': 'ALAN EDUARDO',
  'sexo': 'M'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbcc'),
  'clave_alu': 11050041,
  'ap_paterno': 'VILCHES',
  'ap_materno': 'LINARES',
  'nombre': 'MARIANA',
  'sexo': 'F',
  'ciudad': 'QUERETARO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbd0'),
  'clave_alu': 11050070,
  'ap_paterno': 'MARTINEZ',
  'ap_materno': 'CUELLAR',
  'nombre': 'SUSANA AZUL',
  'sexo': 'F'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbcd'),
  'clave_alu': 11050050,
  'ap_paterno': 'BARRAGAN',
  'ap_materno': 'BAEZA',
  'nombre': 'GLORIA PAULINA',
  'sexo': 'F',
  'ciudad': 'QUERETAROQRO',
  'email': 'paubb90@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbd2'),
  'clave_alu': 11050075,
  'ap_paterno': 'PADILLA',
  'ap_materno': 'BRIZUELA',
  'nombre': 'LUIS DANIEL',
  'ciudad': 'QUERETARO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbdc'),
  'clave_alu': 11050096,
  'ap_paterno': 'CABALLERO DE LOS OLIVOS',
  'ap_materno': 'VALDESPINO',
  'nombre': 'KARLA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'kissyfur_86@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbac'),
  'clave_alu': 11040283,
  'ap_paterno': 'JIMENEZ',
  'ap_materno': 'MENDIBUR',
  'nombre': 'EDGAR ARMANDO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'mendi738@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbd8'),
  'clave_alu': 11050088,
  'ap_paterno': 'VICTORICA',
  'ap_materno': 'BRAVO',
  'nombre': 'GERARDO',
  'ciudad': 'QUERETARO',
  'email': 'ger91_vic09_bra23@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbe3'),
  'clave_alu': 11050120,
  'ap_paterno': 'OLVERA',
  'ap_materno': 'AGUILAR',
  'nombre': 'JUVENAL',
  'email': 'juves_3250aguilar@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbe4'),
  'clave_alu': 11050115,
  'ap_paterno': 'MARTINEZ',
  'ap_materno': 'FRANCO',
  'nombre': 'JUAN CARLOS',
  'ciudad': 'QUERETARO'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbd3'),
  'clave_alu': 11050068,
  'ap_paterno': 'LUIS',
  'ap_materno': 'LUIS',
  'nombre': 'DAVID ALEJANDRO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'crazyhorse_21@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbe1'),
  'clave_alu': 11050113,
  'ap_paterno': 'HERNANDEZ',
  'ap_materno': 'VITAL',
  'nombre': 'ADRIANA ANDREA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'andreavital_30@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbec'),
  'clave_alu': 11050153,
  'ap_paterno': 'LOO',
  'ap_materno': 'ESTRADA',
  'nombre': 'ANDREA',
  'ciudad': 'QUERETARO',
  'email': 'andrealooe@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbf1'),
  'clave_alu': 11050155,
  'ap_paterno': 'LOPEZ',
  'ap_materno': 'SALDA',
  'nombre': 'LESLIE EDITH',
  'sexo': 'F'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbde'),
  'clave_alu': 11050102,
  'ap_paterno': 'CHAVEZ',
  'ap_materno': 'MU',
  'nombre': 'ANDREA',
  'sexo': 'F'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbd4'),
  'clave_alu': 11050076,
  'ap_paterno': 'PRADO',
  'ap_materno': 'PE',
  'nombre': 'KARLA PATRICIA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'azulviajes@prodigy.net.mx'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbea'),
  'clave_alu': 11050141,
  'ap_paterno': 'CRUZ',
  'ap_materno': 'ABAD',
  'nombre': 'ALEJANDRA',
  'sexo': 'F',
  'ciudad': 'QUERETARO',
  'email': 'nopalita_10@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbee'),
  'clave_alu': 11050152,
  'ap_paterno': 'JUAREZ',
  'ap_materno': 'URBINA',
  'nombre': 'EDUARDO ALEJANDRO',
  'sexo': 'M',
  'ciudad': 'QUERETARO',
  'email': 'eduard_dunno@email.com'},
 {'_id': ObjectId('5f873e4a7591b0b48f65fbf3'),
  'clave_alu': 11050177,

In [9]:
df_mongo = pd.DataFrame(lista_f)
df_mongo

,_id,clave_alu,ap_paterno,ap_materno,nombre,sexo,ciudad,email,materias,evaluaciones
0,5f873e4a7591b0b48f65faf9,11030177,FERRUSCA,ANDRADE,OCTAVIO,M,QUERETARO,tavoferrus_11@email.com,NaN,NaN
1,5f873e4a7591b0b48f65faf6,11030172,BORBOLLA,RAMOS,ARGELIA,F,QUERETARO,kargi_gogos@email.com,NaN,NaN
2,5f873e4a7591b0b48f65fafc,11030199,ROSALES,APREZA,NESTOR MARTIN,M,QUERETARO,nestoriwh@hotmai.com,NaN,NaN
3,5f873e4a7591b0b48f65fb04,11030217,FERRUSCA,ANDRADE,CESAR,M,QUERETARO,cesar_tum-b@email.com,NaN,NaN
4,5f873e4a7591b0b48f65fafb,11030173,CASTRO,MANCERA,KARLA MARIANA,F,SANTIAGO DE QUERETARO,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
197,5f873e4a7591b0b48f65fe1a,14080001,MEJIA,JIMENEZ,LUISA,NaN,NaN,NaN,NaN,NaN
198,5f873e4a7591b0b48f65fe1d,12080001,,,,NaN,NaN,NaN,NaN,NaN
199,5f873e4a7591b0b48f65fe19,14080002,MEJIA,JIMENEZ,LUISA,NaN,NaN,NaN,NaN,NaN
200,5f873e4a7591b0b48f65fe1b,14080003,MEJIA,JIMENEZ,LUISA,NaN,NaN,NaN,NaN,NaN
201,5f873e4a7591b0b48f65fe1c,14080004,MEJIA,JIMENEZ,LUISA,NaN,NaN,NaN,NaN,NaN

## Conexion Mediante HTML

In [10]:
url = 'https://es.wikipedia.org/wiki/ISO_3166-2:MX'
df_html = pd.read_html(url)
print(type(df_html))
df_html

<class 'list'>

[                                               Estado  \
 0                                      Aguascalientes
 1                                     Baja California
 2                                 Baja California Sur
 3                                            Campeche
 4                                             Chiapas
 5                                           Chihuahua
 6                                    Ciudad de M√©xico
 7                                            Coahuila
 8                                              Colima
 9                                             Durango
 10                                         Guanajuato
 11                                           Guerrero
 12                                            Hidalgo
 13                                            Jalisco
 14                                             M√©xico
 15                                          Michoac√°n
 16                                            Morelos
 17                                            Nayarit
 18                                         Nuevo Le√≥n
 19                                             Oaxaca
 20                                             Puebla
 21                                          Quer√©taro
 22                                       Quintana Roo
 23                                    San Luis Potos√≠
 24                                            Sinaloa
 25                                             Sonora
 26                                            Tabasco
 27                                         Tamaulipas
 28                                           Tlaxcala
 29                                           Veracruz
 30                                            Yucat√°n
 31                                          Zacatecas
 32  Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...

                                              Variable  \
 0                                                Ags.
 1                                                B.C.
 2                                              B.C.S.
 3                                               Camp.
 4                                               Chis.
 5                                               Chih.
 6                                             C.D.Mx.
 7                                               Coah.
 8                                                Col.
 9                                                Dgo.
 10                                               Gto.
 11                                               Gro.
 12                                               Hgo.
 13                                               Jal.
 14                                      Edo. M√©x.[D]‚Äã
 15                                              Mich.
 16                                               Mor.
 17                                               Nay.
 18                                               N.L.
 19                                               Oax.
 20                                               Pue.
 21                                               Qro.
 22                                        Q. Roo.[F]‚Äã
 23                                             S.L.P.
 24                                               Sin.
 25                                               Son.
 26                                               Tab.
 27                                             Tamps.
 28                                              Tlax.
 29                                               Ver.
 30                                               Yuc.
 31                                               Zac.
 32  Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...

                                            RENAPO[A]‚Äã  \
 0                                                  AS
 1                                                  BC
 2                                                  BS
 3                                                  CC
 4                                                  CS
 5                                                  CH
 6                                                  DF
 7                                                  CL
 8                                                  CM
 9                                                  DG
 10                                                 GT
 11                                                 GR
 12                                                 HG
 13                                                 JC
 14                                                 MC
 15                                                 MN
 16                                                 MS
 17                                                 NT
 18                                                 NL
 19                                                 OC
 20                                                 PL
 21                                                 QO
 22                                                 QR
 23                                                 SP
 24                                                 SL
 25                                                 SR
 26                                                 TC
 27                                                 TS
 28                                                 TL
 29                                                 VZ
 30                                                 YN
 31                                                 ZS
 32  Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...

                                            Dos letras  \
 0                                                  AG
 1                                                  BC
 2                                                  BS
 3                                                  CM
 4                                                  CS
 5                                                  CH
 6                                              CX[B]‚Äã
 7                                                  CO
 8                                                  CL
 9                                                  DG
 10                                                 GT
 11                                                 GR
 12                                                 HG
 13                                                 JC
 14                                             EM[E]‚Äã
 15                                                 MI
 16                                                 MO
 17                                                NaN
 18                                                 NL
 19                                                 OA
 20                                                 PU
 21                                                 QT
 22                                                 QR
 23                                                 SL
 24                                                 SI
 25                                                 SO
 26                                                 TB
 27                                                 TM
 28                                                 TL
 29                                                 VE
 30                                                 YU
 31                                                 ZA
 32  Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...

                                 Completo (ISO 3166-2)
 0                                              MX-AGU
 1                                              MX-BCN
 2                                              MX-BCS
 3                                              MX-CAM
 4                                              MX-CHP
 5                                              MX-CHH
 6                                          MX-CMX[C]‚Äã
 7                                              MX-COA
 8                                              MX-COL
 9                                              MX-DUR
 10                                             MX-GUA
 11                                             MX-GRO
 12                                             MX-HID
 13                                             MX-JAL
 14                                             MX-MEX
 15                                             MX-MIC
 16                                             MX-MOR
 17                                             MX-NAY
 18                                             MX-NLE
 19                                             MX-OAX
 20                                             MX-PUE
 21                                             MX-QUE
 22                                             MX-ROO
 23                                             MX-SLP
 24                                             MX-SIN
 25                                             MX-SON
 26                                             MX-TAB
 27                                             MX-TAM
 28                                             MX-TLA
 29                                             MX-VER
 30                                             MX-YUC
 31                                             MX-ZAC
 32  Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...  ,
                         0                                   1
 0  Control de autoridades  Proyectos Wikimedia  Datos: Q28197]

In [11]:
print(type(df_html[0]))
df_html[0]

<class 'pandas.core.frame.DataFrame'>

,Estado,Variable,RENAPO[A]‚Äã,Dos letras,Completo (ISO 3166-2)
0,Aguascalientes,Ags.,AS,AG,MX-AGU
1,Baja California,B.C.,BC,BC,MX-BCN
2,Baja California Sur,B.C.S.,BS,BS,MX-BCS
3,Campeche,Camp.,CC,CM,MX-CAM
4,Chiapas,Chis.,CS,CS,MX-CHP
5,Chihuahua,Chih.,CH,CH,MX-CHH
6,Ciudad de M√©xico,C.D.Mx.,DF,CX[B]‚Äã,MX-CMX[C]‚Äã
7,Coahuila,Coah.,CL,CO,MX-COA
8,Colima,Col.,CM,CL,MX-COL
9,Durango,Dgo.,DG,DG,MX-DUR
10,Guanajuato,Gto.,GT,GT,MX-GUA
11,Guerrero,Gro.,GR,GR,MX-GRO
12,Hidalgo,Hgo.,HG,HG,MX-HID
13,Jalisco,Jal.,JC,JC,MX-JAL
14,M√©xico,Edo. M√©x.[D]‚Äã,MC,EM[E]‚Äã,MX-MEX
15,Michoac√°n,Mich.,MN,MI,MX-MIC
16,Morelos,Mor.,MS,MO,MX-MOR
17,Nayarit,Nay.,NT,NaN,MX-NAY
18,Nuevo Le√≥n,N.L.,NL,NL,MX-NLE
19,Oaxaca,Oax.,OC,OA,MX-OAX
20,Puebla,Pue.,PL,PU,MX-PUE
21,Quer√©taro,Qro.,QO,QT,MX-QUE
22,Quintana Roo,Q. Roo.[F]‚Äã,QR,QR,MX-ROO
23,San Luis Potos√≠,S.L.P.,SP,SL,MX-SLP
24,Sinaloa,Sin.,SL,SI,MX-SIN
25,Sonora,Son.,SR,SO,MX-SON
26,Tabasco,Tab.,TC,TB,MX-TAB
27,Tamaulipas,Tamps.,TS,TM,MX-TAM
28,Tlaxcala,Tlax.,TL,TL,MX-TLA
29,Veracruz,Ver.,VZ,VE,MX-VER
30,Yucat√°n,Yuc.,YN,YU,MX-YUC
31,Zacatecas,Zac.,ZS,ZA,MX-ZAC
32,Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...,Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...,Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...,Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...,Notas: ‚Üë Registro Nacional de Poblaci√≥n M√©xico...

In [12]:
print(df_html[0].index)
df_html[0].drop(32, axis=0, inplace=True)
df_html[0]

RangeIndex(start=0, stop=33, step=1)

,Estado,Variable,RENAPO[A]‚Äã,Dos letras,Completo (ISO 3166-2)
0,Aguascalientes,Ags.,AS,AG,MX-AGU
1,Baja California,B.C.,BC,BC,MX-BCN
2,Baja California Sur,B.C.S.,BS,BS,MX-BCS
3,Campeche,Camp.,CC,CM,MX-CAM
4,Chiapas,Chis.,CS,CS,MX-CHP
5,Chihuahua,Chih.,CH,CH,MX-CHH
6,Ciudad de M√©xico,C.D.Mx.,DF,CX[B]‚Äã,MX-CMX[C]‚Äã
7,Coahuila,Coah.,CL,CO,MX-COA
8,Colima,Col.,CM,CL,MX-COL
9,Durango,Dgo.,DG,DG,MX-DUR
10,Guanajuato,Gto.,GT,GT,MX-GUA
11,Guerrero,Gro.,GR,GR,MX-GRO
12,Hidalgo,Hgo.,HG,HG,MX-HID
13,Jalisco,Jal.,JC,JC,MX-JAL
14,M√©xico,Edo. M√©x.[D]‚Äã,MC,EM[E]‚Äã,MX-MEX
15,Michoac√°n,Mich.,MN,MI,MX-MIC
16,Morelos,Mor.,MS,MO,MX-MOR
17,Nayarit,Nay.,NT,NaN,MX-NAY
18,Nuevo Le√≥n,N.L.,NL,NL,MX-NLE
19,Oaxaca,Oax.,OC,OA,MX-OAX
20,Puebla,Pue.,PL,PU,MX-PUE
21,Quer√©taro,Qro.,QO,QT,MX-QUE
22,Quintana Roo,Q. Roo.[F]‚Äã,QR,QR,MX-ROO
23,San Luis Potos√≠,S.L.P.,SP,SL,MX-SLP
24,Sinaloa,Sin.,SL,SI,MX-SIN
25,Sonora,Son.,SR,SO,MX-SON
26,Tabasco,Tab.,TC,TB,MX-TAB
27,Tamaulipas,Tamps.,TS,TM,MX-TAM
28,Tlaxcala,Tlax.,TL,TL,MX-TLA
29,Veracruz,Ver.,VZ,VE,MX-VER
30,Yucat√°n,Yuc.,YN,YU,MX-YUC
31,Zacatecas,Zac.,ZS,ZA,MX-ZAC

In [13]:
url1 = 'https://en.wikipedia.org/w/index.php?title=Solar_power&oldid=1022764142'
df_html2 = pd.read_html(url1)
print(type(df_html2))
print("Numero de tablas en DF", len(df_html2))

<class 'list'>
Numero de tablas en DF 22

In [14]:
df_html2[2]

,Name,Country,Capacity MWp,Generation GWh p.a.,Size km2,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Year,Ref
0,Pavagada Solar Park,India,2050,NaN,53,2017,[2][53][54]
1,Tengger Desert Solar Park,China,1547,NaN,43,2016,[55][56]
2,Bhadla Solar Park,India,1515,NaN,40,2017,[57][58][59]
3,Kurnool Ultra Mega Solar Park,India,1000,NaN,24,2017,[60]
4,Datong Solar Power Top Runner Base,China,1000,NaN,NaN,2016,[61][62][63]
5,Longyangxia Dam Solar Park,China,850,NaN,23,2015,[64][65][66][67][68]
6,Rewa Ultra Mega Solar,India,750,NaN,NaN,2018,[69]
7,Kamuthi Solar Power Project,India,648,NaN,10.1,2016,[70][71]
8,Solar Star (I and II),United States,579,1664.0,13,2015,[72][73]
9,Topaz Solar Farm,United States,550,1301.0,24.6[74],2014,[75][76][77]

In [15]:
i = 0
for dfh in df_html2:
    print(str(i).center(60,"*"))
    dfh.info()
    i = i + 1

*****************************0******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7 non-null      object
dtypes: object(1)
memory usage: 184.0+ bytes
*****************************1******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   (Solar Electricity Generation, Year)          16 non-null     object
 1   (Solar Electricity Generation, Energy (TWh))  16 non-null     object
 2   (Solar Electricity Generation, % of Total)    16 non-null     object
dtypes: object(3)
memory usage: 512.0+ bytes
*****************************2******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   Name                                                                         10 non-null     object
 1   Country                                                                      10 non-null     object
 2   Capacity MWp                                                                 10 non-null     int64
 3   Generation GWh p.a.                                                          2 non-null      float64
 4   Size km2                                                                     8 non-null      object
 5   .mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Year  10 non-null     int64
 6   Ref                                                                          10 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 688.0+ bytes
*****************************3******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           11 non-null     object
 1   Capacity (MW)  11 non-null     object
 2   Location       11 non-null     object
 3   Notes          11 non-null     object
dtypes: object(4)
memory usage: 480.0+ bytes
*****************************4******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       0 non-null      float64
 1   1       1 non-null      object
dtypes: float64(1), object(1)
memory usage: 144.0+ bytes
*****************************5******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       0 non-null      float64
 1   1       1 non-null      object
dtypes: float64(1), object(1)
memory usage: 144.0+ bytes
*****************************6******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      object
dtypes: object(1)
memory usage: 144.0+ bytes
*****************************7******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   vteSolar energy    24 non-null     object
 1   vteSolar energy.1  24 non-null     object
 2   vteSolar energy.2  2 non-null      object
dtypes: object(3)
memory usage: 704.0+ bytes
*****************************8******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6 non-null      object
 1   1       6 non-null      object
dtypes: object(2)
memory usage: 224.0+ bytes
*****************************9******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      object
 1   1       3 non-null      object
dtypes: object(2)
memory usage: 176.0+ bytes
*****************************10*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8 non-null      object
 1   1       8 non-null      object
dtypes: object(2)
memory usage: 256.0+ bytes
*****************************11*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   vteSolar power by country    8 non-null      object
 1   vteSolar power by country.1  8 non-null      object
dtypes: object(2)
memory usage: 256.0+ bytes
*****************************12*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vtePhotovoltaics    22 non-null     object
 1   vtePhotovoltaics.1  22 non-null     object
dtypes: object(2)
memory usage: 480.0+ bytes
*****************************13*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      object
 1   1       3 non-null      object
dtypes: object(2)
memory usage: 176.0+ bytes
*****************************14*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      object
 1   1       3 non-null      object
dtypes: object(2)
memory usage: 176.0+ bytes
*****************************15*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      object
 1   1       5 non-null      object
dtypes: object(2)
memory usage: 208.0+ bytes
*****************************16*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      object
 1   1       3 non-null      object
dtypes: object(2)
memory usage: 176.0+ bytes
*****************************17*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      object
 1   1       2 non-null      object
dtypes: object(2)
memory usage: 160.0+ bytes
*****************************18*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   vteElectricity delivery    11 non-null     object
 1   vteElectricity delivery.1  11 non-null     object
 2   vteElectricity delivery.2  1 non-null      object
dtypes: object(3)
memory usage: 392.0+ bytes
*****************************19*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      object
 1   1       2 non-null      object
dtypes: object(2)
memory usage: 160.0+ bytes
*****************************20*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   vteRenewable energy by country and territory    9 non-null      object
 1   vteRenewable energy by country and territory.1  9 non-null      object
dtypes: object(2)
memory usage: 272.0+ bytes
*****************************21*****************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      object
 1   1       2 non-null      object
dtypes: object(2)
memory usage: 160.0+ bytes

In [ ]:
url2 = 'http://ingenieria.aragon.unam.mx/ico/alumnos/examenes_extraordinarios.rb'
df_html3 = pd.read_html(url2)
print(type(df_html3))
print("Numero de tablas en DF", len(df_html3))

## TAREA

###  DF con varias tablas de una URL

In [17]:
url4 = 'https://es.wikipedia.org/wiki/Europa'
df_html4 = pd.read_html(url4)
print(type(df_html4))
print("Numero de tablas en DF:", len(df_html4))

<class 'list'>
Numero de tablas en DF: 13

In [18]:
df_html4[1]

,Bandera,Nombre/Nombre oficial,Establecido,Superficie (km¬≤),Poblaci√≥n,Habitantes por km¬≤,Capital,Idioma(s) oficial(es)
0,NaN,Albania Rep√∫blica de Albania,1912,28¬†748,3¬†038¬†594,1056,Tirana,sq
1,NaN,Alemania Rep√∫blica Federal de Alemania,1871,357¬†022,80¬†722¬†792,2261,Berl√≠n,de
2,NaN,Andorra Coprincipado de Andorra,1278,468,85¬†660,183,Andorra la Vieja,ca
3,NaN,Armenia Rep√∫blica de Armenia,1991,29¬†749,3¬†229¬†900,1085,Erev√°n,hy
4,NaN,Austria Rep√∫blica de Austria,1918,83¬†871,8¬†711¬†770,1038,Viena,de
5,NaN,Azerbaiy√°n Rep√∫blica de Azerbaiy√°n,1991,86¬†600,9¬†872¬†765,114,Bak√∫,az
6,NaN,B√©lgica Reino de B√©lgica,1830,30¬†528,11¬†409¬†077,3737,Bruselas,nl/fr/de
7,NaN,Bielorrusia Rep√∫blica de Bielorrusia,1991,207¬†600,9¬†570¬†376,461,Minsk,ru/be
8,NaN,Bosnia y Herzegovina,1992,51¬†917,3¬†861¬†912,754,Sarajevo,bs/hr/sr
9,NaN,Bulgaria Rep√∫blica de Bulgaria,1908,110¬†879,7¬†144¬†653,644,Sof√≠a,bg
10,NaN,Chipre Rep√∫blica de Chipre,1960,9251,1¬†205¬†575,1303,Nicosia,el/tk
11,NaN,Croacia Rep√∫blica de Croacia,1991,56¬†594,4¬†313¬†707,762,Zagreb,hr
12,NaN,Dinamarca Reino de Dinamarca,935,43¬†094,5¬†593¬†785,1298,Copenhague,da/fo/kl
13,NaN,Eslovaquia Rep√∫blica Eslovaca,1993,49¬†035,5¬†445¬†802,111,Bratislava,sk
14,NaN,Eslovenia Rep√∫blica de Eslovenia,1991,20¬†273,1¬†978¬†029,975,Liubliana,sl
15,NaN,Espa√±a Reino de Espa√±a,1516,505¬†370,47¬†435¬†597,94,Madrid,es/ca/gl/eu
16,NaN,Estonia Rep√∫blica de Estonia,1991,45¬†228,1¬†258¬†545,278,Tallin,et
17,NaN,Finlandia Rep√∫blica de Finlandia,1918,338¬†415,5¬†948¬†211,162,Helsinki,fi/sv
18,NaN,Francia Rep√∫blica Francesa,843,643¬†801,66¬†836¬†154,1038,Par√≠s,fr
19,NaN,Georgia Estado de Georgia,1991,69¬†700,4¬†928¬†052,707,Tiflis,ka
20,NaN,Grecia Rep√∫blica Hel√©nica,1832,131¬†957,10¬†773¬†253,816,Atenas,el
21,NaN,Hungr√≠a,1918,93¬†028,9¬†874¬†784,1061,Budapest,hu
22,NaN,Irlanda Rep√∫blica de Irlanda,1937,70¬†273,4¬†952¬†473,704,Dubl√≠n,ga/en
23,NaN,Islandia Rep√∫blica de Islandia,1944,103¬†000,335¬†878,32,Reikiavik,is
24,NaN,Italia Rep√∫blica Italiana,1861,301¬†340,62¬†007¬†540,2057,Roma,it
25,NaN,Letonia Rep√∫blica de Letonia,1991,64¬†589,1¬†965¬†686,304,Riga,lv
26,NaN,Liechtenstein Principado de Liechtenstein,1719,160,37¬†937,2371,Vaduz,de
27,NaN,Lituania Rep√∫blica de Lituania,1991,65¬†300,2¬†854¬†235,437,Vilna,lt
28,NaN,Luxemburgo Gran Ducado de Luxemburgo,1890,2586,582¬†291,2251,Ciudad de Luxemburgo,lb/fr/de
29,NaN,Macedonia del Norte Rep√∫blica de Macedonia del...,1991,25¬†713,2¬†100¬†025,816,Skopie,mk/sq
30,NaN,Malta Rep√∫blica de Malta,1974,316,415¬†196,13139,La Valeta,mt/en
31,NaN,Moldavia Rep√∫blica de Moldavia,1991,33¬†851,3¬†510¬†485,1037,Chisin√°u,ro
32,NaN,M√≥naco Principado de M√≥naco,1861,2,30¬†581,"15¬†290,5",Ciudad de M√≥naco,fr
33,NaN,Montenegro,2006,13¬†812,644¬†578,466,Podgorica,n/d
34,NaN,Noruega Reino de Noruega,1905,323¬†802,5¬†265¬†158,162,Oslo,no
35,NaN,Pa√≠ses Bajos Reino de los Pa√≠ses Bajos,1815,41¬†543[18]‚Äã,17¬†016¬†967,4096,√Åmsterdam,nl
36,NaN,Polonia Rep√∫blica de Polonia,1918,312¬†685,38¬†652¬†326,1232,Varsovia,pl
37,NaN,Portugal Rep√∫blica Portuguesa,1139,92¬†090[19]‚Äã,10¬†833¬†816,1176,Lisboa,pt
38,NaN,Reino Unido Reino Unido de Gran Breta√±a e Irla...,1801,243¬†610,64¬†430¬†428,2644,Londres,en/cy/gd/ga
39,NaN,Rep√∫blica Checa,1993,78¬†867,10¬†644¬†842,1349,Praga,cs
40,NaN,Rumania,1878,238¬†391,21¬†599¬†736,906,Bucarest,ro
41,NaN,Rusia Federaci√≥n Rusa,1547,17¬†098¬†242,142¬†355¬†415,83,Mosc√∫,ru
42,NaN,San Marino Seren√≠sima Rep√∫blica de San Marino,1243,61,33¬†285,5456,Ciudad de San Marino,it
43,NaN,Serbia Rep√∫blica de Serbia,1878,77¬†474,7¬†143¬†921,9292,Belgrado,sr
44,NaN,Suecia Reino de Suecia,1523,450¬†295,9¬†880¬†604,219,Estocolmo,sv
45,NaN,Suiza Confederaci√≥n Suiza,1815,41¬†277,8¬†179¬†294,1981,Berna,de/fr/it/rm
46,NaN,Turqu√≠a Rep√∫blica de Turqu√≠a,1923,783¬†562,84¬†614¬†362,110,Ankara,tr
47,NaN,Ucrania,1991,603¬†550,44¬†209¬†733,732,Kiev,uk
48,NaN,Uni√≥n Europea,1993,4¬†324¬†782,513¬†949¬†445,1188,Bruselas,24
49,NaN,Vaticano Estado de la Ciudad del Vaticano,1929,044,1000,22727,Ciudad del Vaticano,la/it
50,NaN,NaN,Total,10¬†530¬†751,743¬†704¬†000,700,NaN,NaN

In [38]:
df_html4[2]

,Bandera,Nombre/ Nombre oficial,Declaraci√≥n,Superficie (km¬≤),Poblaci√≥n,Densidad de poblaci√≥n (por km¬≤),Capital,Idioma(s) oficial(es)
0,NaN,Abjasia Rep√∫blica de Abjasia,2008,8432,216¬†000,2824,Sujumi,ab/ru
1,NaN,Kosovo Rep√∫blica de Kosovo,2008,10¬†887,1¬†883¬†018,1729,Pristina,sq/sr
2,NaN,Rep√∫blica de Artsaj,1991,11¬†458,138¬†800,1211,Stepanakert,hy
3,NaN,Rep√∫blica Turca del Norte de Chipre,1983,3355,265¬†100,86,Nicosia,tk
4,NaN,Osetia del Sur Rep√∫blica de Osetia del Sur,2008,3900,70¬†000,21,Tsjinval,os/ru/ka
5,NaN,Transnistria Rep√∫blica Moldava Pridnestroviana,1990,4163,537¬†000,133,Tir√°spol,ru/ro/uk
6,NaN,NaN,Total,42¬†195,3¬†031¬†738,718,NaN,NaN

In [39]:
df_html4[3]

,Bandera,Nombre/ Nombre oficial,Estatus,Estado,Superficie (km¬≤),Poblaci√≥n,Habitantes por km¬≤,Capital,Idioma(s) oficial(es)
0,NaN,Acrotiri y Dhekelia Territorio de ultramar,1960.0,Reino Unido,123,15¬†700,1276,Episkopi,en
1,NaN,Gibraltar Territorio de ultramar,2002.0,Reino Unido,59,29¬†328,41897,Gibraltar,en
2,NaN,Bail√≠a de Guernsey Dependencia de la Corona,1204.0,Reino Unido,78,66¬†297,8499,Saint Peter Port,en/fr
3,NaN,Bail√≠a de Jersey Dependencia de la Corona,1204.0,Reino Unido,116,98¬†069,8454,Saint Helier,en/fr
4,NaN,Isla de Man Dependencia de la Corona,1765.0,Reino Unido,572,88¬†195,1541,Douglas,en/gv
5,NaN,Svalbard Territorio de ultramar,2002.0,Noruega,62¬†045,1872,3,Longyearbyen,no
6,NaN,NaN,NaN,Total,"62¬†939,9",299¬†461,5,NaN,NaN

In [40]:
df_html4[5]

    Pa√≠ses                    Moneda
0      NaN             Euro (‚Ç¨, EUR)
1      NaN  Libra esterlina (¬£, GBP)
2      NaN        Franco suizo (CHF)
3      NaN          Rublo ruso (RUB)
4      NaN             Corona danesa
5      NaN                       Lek
6      NaN    Rublo bielorruso (BYR)
7      NaN   Marco convertible (BHK)
8      NaN                 Lev (BGN)
9      NaN            Flor√≠n h√∫ngaro
10     NaN    Corona islandesa (ISK)
11     NaN               Tenge (KZT)
12     NaN     Dinar macedonio (MKD)
13     NaN         Leu moldavo (MDL)
14     NaN          Corona (kr, NOK)
15     NaN              Esloti (PLN)
16     NaN        Corona checa (CZK)
17     NaN                 Leu (RON)
18     NaN               Dinar (RSD)
19     NaN          Corona (kr, SEK)
20     NaN              Grivna (UAH)

### DF alumnos "bdcolegio02"

In [21]:
from sqlalchemy import create_engine

us = 'fesalu'
passwd = 'bdfes2023'
url = 'bd.arcelia.net'
puerto = '3306'
bd = 'bdcolegio02'
auth = 'mysql_native_password'

str_conn = 'mysql+mysqlconnector://{0}:{1}@{2}:{3}/{4}?auth_plugin={5}'
str_conn = str_conn.format(us, passwd, url, puerto, bd, auth)
str_conn

'mysql+mysqlconnector://fesalu:bdfes2023@bd.arcelia.net:3306/bdcolegio02?auth_plugin=mysql_native_password'

In [22]:
conn = create_engine(str_conn)
conn

Engine(mysql+mysqlconnector://fesalu:***@bd.arcelia.net:3306/bdcolegio02?auth_plugin=mysql_native_password)

In [32]:
sql = '''SELECT * FROM alumnos WHERE sexo = 'M' '''
df_mysql = pd.read_sql_query(sql=sql, con=conn)
print(type(df_mysql))
df_mysql

<class 'pandas.core.frame.DataFrame'>

,clave_alu,clave_admin,ap_paterno,ap_materno,nombre,sexo,curp,peso,estatura,direccion,colonia,cp,ciudad,id_estado,delegacion,telefono,celular,email,status_alu,fedita
0,11030177,4716,FERRUSCA,ANDRADE,OCTAVIO,M,,62.0,1.68,MARQUES DE BARCELO #608,LOMAS DEL MARUQES,26146,QUERETARO,22,QUERETARO,4458114845,9618114845,tavoferrus_11@miemail.com,AC,2021-10-15 16:23:00
1,11030178,4720,GARCIA,GOMEZ,RAFAEL,M,220140190055288,55.0,1.82,PAJAROS # 687,CALESA SEGUNDA SECCION,26020,QUERETARO,22,QUERETARO,4451986967,9611986967,arobertogarcia@telmart.net.mx,AC,2021-10-25 09:22:33
2,11030180,5380,GUTIERREZ,FLORES,CARLOS DAVID,M,GUFC910124HDFTLR04,60.0,1.75,CIRCUITO SAN IGNACIO 670 INT 6,FRACCIONAMIENTO SANTIAGO,26129,QUERETARO,22,SANTIAGO DE QUERETARO,4455558865,9612558865,chorok_skp91@miemail.com,AC,2021-09-27 21:52:05
3,11030188,4857,MARTINEZ,RIVERA,JAVIER JOSUE,M,MARJ910422HQTRVV01,52.0,1.66,ASUNCION NO. 698,EL ROSARIO,26128,QUERETRO,22,QUERETARO,0444458817907,0449618817907,c_h_a_p_a_r_r_o-pi_cha_ka@miemail.com,AC,2022-10-11 20:23:14
4,11030199,4769,ROSALES,APREZA,NESTOR MARTIN,M,,53.0,1.63,RIO BALSAS #707,LOS ARQUITOS,26050,QUERETARO,22,QUERETARO SUR,0444458591085,0449618291082,nestoriwh@hotmai.com,AC,2021-09-22 17:57:13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,11080203,,VILLAGRANA,BARRAGAN,CARLOS IVAN,M,VIBC911114HDFLRR06,61.0,1.72,MARQUES DE LAS AMARILLAS NO. 687,LOMAS DEL MARQUES,26146,QUERETARO,22,SANTIAGO DE QUERETARO,4458517765,9618517765,chino-vergoza@miemail.com,AS,2023-03-08 16:53:59
395,11080204,,AGUILLON,RESENDIZ,JOSE,M,AURJ941216HQTGSS06,57.0,160.00,EULOGIO MARROQUIN 707,CANDILES,26190,QUERETARO,22,CORREGIDORA,4458170450,9618170420,blackjarrior_9412@miemail.com,AS,2023-03-10 11:05:13
396,11080206,,NAVA,TORRES,LEONARDO JESUS,M,NATL9408HDFVRN05,0.0,0.00,PASEO DE MOSCU #868,TEJEDA,26190,QUERETARO,22,SANTIAGO DE QUERETARO,4458770708,9618770708,leo94-88@infinitum.com.mx,AS,2023-03-11 19:56:28
397,11080207,,LOPEZ,AGUILAR,DANIEL,M,LOAD940404HBCPGN06,0.0,0.00,HDA DE LOS MORALES # 707,RINCON DE LOS ARCOS,36636,IRPUATO,12,IRAPUATO,4651551906,4621251906,marydm72@miemail.com,AS,2023-03-07 11:17:06
398,11080210,,GUERRERO,COLOMBRES,ALDO ENRICO,M,GUCA960125HDFRLL09,44.0,1.59,AVENIDA PE,SAN PEDRITO PE,,SANTIAGO DE QUERETARO,22,,5585511084,5582211084,colombresm@att.com.mx,AS,2023-04-15 20:48:37